version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Api.Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: "kzE5(g26rBs$j+Py"
            ACCEPT_EULA: "Y"