version: "3"
services:
    ui:
        build:
            context: .
            dockerfile: Ui.Dockerfile
        ports:
            - "7081:80"
        depends_on:
            - api
    api:
        build:
            context: .
            dockerfile: Api.Dockerfile
        ports:
            - "7080:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/azure-sql-edge"
        environment:
            MSSQL_SA_PASSWORD: "kzE5(g26rBsj+Py"
            ACCEPT_EULA: "Y"